services:
  opengauss:
    container_name: opengauss-web-db
    image: enmotech/opengauss:3.0.0
    restart: always
    privileged: true
    environment:
      - GS_PASSWORD=Root123456
      - TZ=Asia/Shanghai
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"
